apiVersion: v1
kind: ServiceAccount
metadata:
  name: trickster
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trickster
rules:
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trickster
  namespace: default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: trickster
subjects:
- kind: ServiceAccount
  name: trickster
  namespace: default

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: trickster
  namespace: default
  annotations:
    kubernetes.io/service-account.name: trickster
