apiVersion: v1
kind: ServiceAccount
metadata:
  name: trickster
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trickster
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trickster
  namespace: monitoring
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: trickster
subjects:
- kind: ServiceAccount
  name: trickster
  namespace: default

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: trickster
  namespace: default
  annotations:
    kubernetes.io/service-account.name: trickster
