backends:
  k8s:
    origin_url: https://dc773136-2db3-4474-a6ea-20461c67ca54.cpc1-us-central.linodelke.net:443/api/v1/namespaces/monitoring/services/http:prometheus-kube-prometheus-prometheus:9090/proxy/
    provider: prometheus
    req_rewriter_name: k8s
    tls:
      certificate_authority_paths:
      - /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/ca.crt
frontend:
  listen_port: 9090
logging:
  log_level: info
metrics:
  listen_port: 8481
request_rewriters:
  k8s:
    instructions:
    - - header
      - set
      - Authorization
      - Bearer ***
