#
# Trickster 2.0 Example Configuration File - Example Prometheus Accelerator
#
# To use this, run: trickster -config /path/to/simple.prometheus.yaml
#
# This file demonstrates a basic configuration to accelerate
# Prometheus queries using Trickster. More documentation is
# available at https://github.com/trickstercache/trickster/docs/
#
# Copyright 2018 The Trickster Authors
#

frontend:
  listen_port: 9090

backends:
  default:
    # update FQDN and Port to work in your environment
    origin_url: 'https://127.0.0.1:59353/api/v1/namespaces/monitoring/services/http:kube-prometheus-stack-prometheus:9090/proxy'
    provider: 'prometheus'
    tls:
        insecure_skip_verify: false
        certificate_authority_paths: [ /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/ca.crt ]
        client_cert_path: /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/tls.crt
        client_key_path: /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/tls.key

metrics:
  listen_port: 8481   # available for scraping at http://<trickster>:<metrics.listen_port>/metrics

logging:
  log_level: 'info'
