backends:
  default:
    req_rewriter_name: example_rewriter
    origin_url: https://127.0.0.1:49700/api/v1/namespaces/monitoring/services/http:kube-prometheus-stack-prometheus:9090/proxy/
    provider: prometheus
    tls:
      certificate_authority_paths:
      - /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/ca.crt
      client_cert_path: /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/tls.crt
      client_key_path: /Users/tamal/go/src/github.com/tamalsaha/prometheus-demo/certs/tls.key
frontend:
  listen_port: 9090
logging:
  log_level: info
metrics:
  listen_port: 8481

# https://trickstercache.org/docs/paths/request-rewriters/
request_rewriters:
  example_rewriter:
    instructions:
    - [ 'header', 'set', 'Authorization', 'Basic dGFtYWw6cGFzc3dvcmQ=' ]
