# "message": "services \"http:kube-prometheus-stack-prometheus:9090\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"monitoring\"",
# "reason": "Forbidden",

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-service-proxy
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["get", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-service-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-service-proxy
subjects:
- kind: User
  name: system:anonymous
  apiGroup: rbac.authorization.k8s.io
